[package]
name = "oc-client"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
oc-core.workspace = true
oc-renderer.workspace = true
oc-world.workspace = true
winit.workspace = true
raw-window-handle.workspace = true
glam.workspace = true
anyhow.workspace = true
tracing.workspace = true
