[package]
name = "oc-client"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
oc-core.workspace = true
oc-renderer.workspace = true
oc-world.workspace = true
winit.workspace = true
raw-window-handle.workspace = true
glam.workspace = true
rayon.workspace = true
anyhow.workspace = true
tracing.workspace = true
oc-protocol.workspace = true
oc-server.workspace = true
oc-assets.workspace = true
serde.workspace = true
ron.workspace = true
rodio = { version = "0.22.2", default-features = false, features = ["playback", "wav"] }
